"""added uid to books

Revision ID: 0a3e48b0c640
Revises: 410166b98b4b
Create Date: 2025-02-11 14:42:44.095309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a3e48b0c640"
down_revision: Union[str, None] = "410166b98b4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("user_uid", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "books", "users", ["user_uid"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "user_uid")
    # ### end Alembic commands ###
