"""change password from str to byte

Revision ID: c82d40ad3d33
Revises: b086b8a752bd
Create Date: 2025-02-09 10:55:30.944836

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c82d40ad3d33"
down_revision: Union[str, None] = "b086b8a752bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.VARCHAR(),
        type_=sa.LargeBinary(),
        postgresql_using="password_hash::BYTEA",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
